#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CityWave.Android.Resource", IsApplication=true)]

namespace CityWave.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CategoriesTab = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CategoriesTabSelected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int HomeTabCategories = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int HomeTabPlaces = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int HomeTabProfile = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int HomeTabSettings = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int PlacesTab = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int PlacesTabSelected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ProfileTab = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ProfileTabSelected = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int SettingsTab = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int SettingsTabSelected = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int CategoriesListView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CategoriesProgressBar = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CategoryNameTextView = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int CityLayout = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int CityNameTextView = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int CitySpinner = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int LoginButton = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int LogoutButton = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int PasswordEditText = 2131099656;
			
			// aapt resource value: 0x7f06000e
			public const int PlaceAddressTextView = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int PlaceNameTextView = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int PlacePictureImageView = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int PlacesListView = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int PlacesProgressBar = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int SkipButton = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int UsernameEditText = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Categories = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CategoriesListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CitySpinnerItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Home = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Places = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PlacesListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Profile = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Settings = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int app_theme = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int app_theme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
