#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CityWave.Android.Resource", IsApplication=true)]

namespace CityWave.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CategoriesTab = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CategoriesTabSelected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int HomeTabCategories = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int HomeTabPlaces = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int HomeTabProfile = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int HomeTabSettings = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int PlacesTab = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int PlacesTabSelected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ProfileTab = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ProfileTabSelected = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int SettingsTab = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int SettingsTabSelected = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int CityLayout = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int CityNameTextView = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int CitySpinner = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int LoginButton = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int PasswordEditText = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int PlaceNameTextView = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int PlacePictureImageView = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int PlacesListView = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int SkipButton = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int UsernameEditText = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Categories = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CitySpinnerItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Places = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PlacesListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Profile = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int app_theme = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
